name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or whichever version you're using
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: |
          npm run build
          node -e "const fs=require('fs');const config={functionKey:process.env.FUNCTION_KEY};fs.writeFileSync('dist/voice.ui/browser/assets/config.json',JSON.stringify(config));"
        env:
          FUNCTION_KEY: ${{ secrets.FUNCTION_KEY }}
      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          FUNCTION_KEY: ${{ secrets.FUNCTION_KEY }}
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_MOSS_0C85A060F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist/voice.ui/browser" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          skip_app_build: true # Skip build - optional

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_MOSS_0C85A060F }}
          action: "close"
          app_location: "dist/voice.ui/browser" # Add this line
          api_location: "" # Add this line
          output_location: "" # Add this line